# Generated by Django 4.0.dev20210416091810 on 2022-12-12 20:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list_category_comments_bids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_list',
            old_name='items',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categoryName',
        ),
        migrations.RemoveField(
            model_name='auction_list',
            name='Picture',
        ),
        migrations.AddField(
            model_name='auction_list',
            name='imageUrl',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_list',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction_list',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auctions.user'),
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
    ]
