# Generated by Django 4.0.dev20210416091810 on 2022-12-13 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_items_auction_list_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='auctions.category'),
        ),
    ]
