# Generated by Django 4.0.dev20210416091810 on 2022-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_list_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='items',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='items',
        ),
        migrations.AddField(
            model_name='bids',
            name='auctionList',
            field=models.ManyToManyField(blank=True, related_name='auctionListBids', to='auctions.auction_list'),
        ),
        migrations.AddField(
            model_name='comments',
            name='auctionList',
            field=models.ManyToManyField(blank=True, related_name='auctionListComments', to='auctions.auction_list'),
        ),
        migrations.CreateModel(
            name='watchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inWatchList', models.BooleanField(default=False)),
                ('auctionList', models.ManyToManyField(blank=True, related_name='auctionListWatchList', to='auctions.auction_list')),
            ],
        ),
    ]
