# Generated by Django 4.0.dev20210416091810 on 2022-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bids_items_remove_comments_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='inWatchList',
            field=models.BooleanField(default=True),
        ),
    ]
