# Generated by Django 4.0.dev20210416091810 on 2022-12-15 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_watchlist_inwatchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='watchList',
            field=models.ManyToManyField(blank=True, null=True, related_name='auctionWatchList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='watchList',
        ),
    ]
