# Generated by Django 4.0.dev20210416091810 on 2022-12-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_comments_auctionlist_remove_comments_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='auctionList',
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bid', to='auctions.user'),
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_auSction', to='auctions.bids'),
        ),
    ]
