# Generated by Django 4.0.dev20210416091810 on 2022-12-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bids_auctionlist_bids_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='price',
            field=models.FloatField(),
        ),
    ]
