# Generated by Django 4.0.dev20210416091810 on 2022-12-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_auSction', to='auctions.bids'),
        ),
    ]
