# Generated by Django 4.0.dev20210416091810 on 2022-12-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bids_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bids',
            field=models.FloatField(default=0),
        ),
    ]
